### ISSUE TITLE
Provide a `safeLoadAll` option

### ISSUE THREAD

**Issue by lufego** [rollup/plugins#39]
Hi, I have a stream which has multiple documents inside e.g:
```yaml
---
kind: x
apiVersion: v1
spec:
  selector: example1
---
kind: x
apiVersion: v1
spec:
  selector: example2
---
kind: x
apiVersion: v1
spec:
  selector: example3
```

in the plugin you have:

```
let data = YAML.load(yaml);
```

but this causes this error when loading my file `(plugin yaml) YAMLException: expected a single document in the stream, but found more`.

For my workflow I need an option to have it loaded as 

```
let data = YAML.safeLoadAll(yaml);
```
This will load both single and multiple document streams

thanks in advance 🙌🏻
